### ISSUE TITLE
No way to persist data

### ISSUE THREAD

**Issue by ahuffman** [docker-library/drupal#34] opened 2016-02-22 20:39 UTC
There should be a VOLUME entry in the Dockerfile at /var/www/html so that you can install modules and persist data.  Otherwise I'd have to re-build a custom container image to achieve what should be a default.  Please take a look at what Wordpress and Joomla are doing with their Dockerfiles.

**Comment by tianon** [comment] 2016-02-22 20:44
This is a duplicate of #3; please see the discussion over there for some of the challenges we've got for making this happen. :+1:

**Closed by tianon** 2016-02-22 20:44 UTC
